---
apiVersion: v1
kind: Service
metadata:
  name: pipelines-for-containers
  labels:
    app: pipelines-for-containers
  namespace: ci-cd
spec:
  type: NodePort
  ports:
    - port: 7000
      nodePort: 33801
      name: "tcp7000"
    - port: 8000
      nodePort: 33802
      name: "tcp8000"
    - port: 8080
      nodePort: 33803
      name: "tcp8080"
  selector:
    app: pipelines-for-containers
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelines-for-containers
  labels:
    app: pipelines-for-containers
    tier: frontend
  namespace: ci-cd
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pipelines-for-containers
      tier: frontend
  template:
    metadata:
      labels:
        app: pipelines-for-containers
        tier: frontend
    spec:
      containers:
        - image: puppet/pipelines-for-containers:latest
          name: pipelines-for-containers
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: mysql_user
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: mysql_password
            - name: DB_ENDPOINT
              value: mysql://pipelines-for-containers-mariadb.ci-cd.svc.cluster.local:3306/pipelines
              #value: mysql://10.0.210.132:3306/pipelines
          ports:
            - containerPort: 7000
              name: "tcp7000"
            - containerPort: 8000
              name: "tcp8000"
            - containerPort: 8080
              name: "tcp8080"
